### ISSUE TITLE
Encoutered Value Error on Fetril

### ISSUE THREAD

**Issue by bayestrans** [dipamgoswami/FeCAM#6] opened 2024-04-30 13:44 UTC
Hi Authors,

I am trying to reproduce the FeTril baseline with the given script for tiny-imagenet-200.

I am getting the following error.
It throws an error after the first task completion.

![image](https://github.com/dipamgoswami/FeCAM/assets/164960955/5ca7cce8-451f-429a-ba58-88c8b6153b99)

Could you please help to solve this? Has anyone encountered such? These are my args for training

```
{
    "prefix": "train",
    "dataset": "tinyimagenet200",
    "memory_size": 0,
    "shuffle": true,
    "init_cls": 100,
    "increment": 5,
    "model_name": "fetril",
    "convnet_type": "resnet18",
    "device": ["3"],
    "shot": [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
    "seed": [1993],
    "init_epochs": 2,
    "init_lr" : 0.1,
    "init_weight_decay" : 5e-4,
    "epochs" : 2,
    "lr" : 0.05,
    "batch_size" : 128,
    "weight_decay" : 5e-4,
    "num_workers" : 8,
    "T" : 50,
    "tukey" : false,
    "diagonal" : false,
    "per_class" : false,
    "full_cov" : false,
    "shrink" : false,
    "norm_cov" : false
}
```

**Comment by dipamgoswami** [comment] 2024-04-30 15:10
Hi, 
It looks like the issue is in creating the test dataloader for the feature dataset. I will try to debug this and get back to you shortly.

**Comment by kandeldeepak46** [comment] 2024-04-30 18:14
sure, thank you

**Comment by dipamgoswami** [comment] 2024-11-13 09:42
Hi, sorry for the very late response. 

It looks like a minor issue, hopefully resolved by now. If you are still facing issue with the FeTrIL implementation, I would recommend using the original codebase from PyCIL.

**Closed as completed** 2024-11-21 16:33 UTC
